name: shrinkeo
description: "Batch video compression tool for Windows using embedded FFmpeg."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  equatable: ^2.0.7

  # File input
  desktop_drop: ^0.7.1
  file_picker: ^11.0.2

  # Utilities
  path: ^1.9.1
  http: ^1.3.0
  google_fonts: ^6.2.1
  window_manager: ^0.5.1
  local_notifier: ^0.1.6
  path_provider: ^2.1.5
  shared_preferences: ^2.5.5
  package_info_plus: ^9.0.1
  url_launcher: ^6.3.2
  flutter_markdown: ^0.7.7+1
  ffi: ^2.2.0
  cupertino_icons: ^1.0.9
  animated_list_plus: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
